config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :ribbits
  resources :sessions
  resources :users

  get "logout" => "sessions#destroy" , :as => "logout"

  root "users#new"
  get "ribbbits" => "ribbits#index" , :as => "ribbbits"

  get "buddies" => "users#buddies" , :as => "buddies"
  get "mentions" => "users#mentions" , :as => "mentions"

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

end

app/models/ribbit.rb
class Ribbit < ActiveRecord::Base
	belongs_to :user
	default_scope  { order(:created_at => :desc) }

	validates :content , length: { maximum: 140 }
end

app/models/user.rb
require 'digest/md5'
class User < ActiveRecord::Base
	
	has_secure_password
	has_many :ribbits
	before_validation :prep_email
	before_save :create_avatar_url

	has_many :follower_relationships , class_name: 'Relationship', :foreign_key => 'followed_id'
	has_many :followed_relationships , class_name: 'Relationship' , :foreign_key => 'follower_id'
	has_many :followers, through: :follower_relationships
	has_many :followeds, through: :followed_relationships


	validates :email , presence: true, uniqueness: true
	validates :username , presence: true , uniqueness: true
	validates :name , presence: true

	def following user
		self.followeds.include? user
	end
	def follow user
		Relationship.create follower_id: self.id, followed_id: user.id
	end
	private 

	def prep_email
		self.email = self.email.strip.downcase if self.email
	end

	def create_avatar_url
		self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


private

def current_user
	@current_user ||= User.find(session[:user_id]) if  session[:user_id]
end

helper_method :current_user

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		relationship = Relationship.new(rel_params)
		relationship.follower = current_user

		flash[:warning] = "Sorry there is something wrong" unless relationship.save
		redirect_to relationship.followed

	end

	def destroy
		relationship = Relationship.find(params[:id])
		user = relationship.followed
		relationship.destroy
		redirect_to user
	end

private

def rel_params
	params.require(:relationship).permit(:followed_id)
end

end

app/controllers/ribbits_controller.rb
class RibbitsController < ApplicationController

	def index
		@ribbits = Ribbit.all
		@ribbit = Ribbit.new
	end
	def create
		ribbit = Ribbit.new(ribit_params)
		ribbit.user_id = current_user.id

		flash[:error] = "Sorry Your ribbit is over 140 Chars!" unless ribbit.save
		redirect_to "/ribbits"
	end

	def destroy
		@ribbit = Ribbit.find(params[:id])
		@ribbit.destroy
		redirect_to "/ribbbits"
	end

private

def ribit_params
	params.require(:ribbit).permit(:content)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
  	user = User.find_by_username params[:username]

  	if user and user.authenticate(params[:password])
  		session[:user_id] = user.id
      flash[:success] = "You have been logged in"
  		redirect_to current_user
  	else
  		flash[:warning] = "Sorry there is something wrong"
  		redirect_to root_url
  	end

  end

  def destroy
  	session[:user_id] = nil
    flash[:warning] = "You have been logged Out!"
  	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id
			flash[:success]= "Congrats! Welcome to ribbit!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@ribbit = Ribbit.new
		@relationship = Relationship.where(
				follower_id: current_user.id,
				followed_id: @user.id
			).first_or_initialize if current_user
	end

	def buddies
		if current_user
			@ribbit = Ribbit.new
			buddies_id = current_user.followeds.map(&:id)
			@ribbits = Ribbit.where(user_id: buddies_id)	
		end
	end
	def mentions
		@ribbit = Ribbit.new
		@ribbits = Ribbit.where("content LIKE ?" ,"%#{current_user.username}%" )
	end

private

	def user_params
		params.require(:user).permit(:email,:username,:name,:password,:password_confrimation);
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/ribbits_helper.rb
module RibbitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ribbit</title>
  <link rel="stylesheet/less" href="/style.less" />
  <link rel="stylesheet" type="text/css" href="/custom.css">
  <script src="/less.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<div class="wrapper">
		<%= link_to image_tag('/gfx/logo.png') , root_url %>
		<% if current_user %>
			<%= link_to "Public Ribbits" , ribbits_path %> |
			<%= link_to "Profile" , current_user %> |
			<%= link_to "Buddies", "/buddies" %> |
			<%= link_to "Mentions", "/mentions" %> |
			<%= link_to "Logout" , "/logout" %>
		<% else %>
			<%= form_tag sessions_path do %>
			  	<%= text_field_tag :username , nil, placeholder: "Username" %>
			  	<%= password_field_tag :password , nil, placeholder: "Password" %>
			  	<%= submit_tag "Login" %>
			<% end -%>
		<% end -%>
	</div>
</header>

<div id="content">
	<div class="wrapper">
		<% flash.each do |name,msg| %>
			<%= content_tag :div , msg , class: "flash #{name}" %>
		<% end %>	
	<%= yield %>
	</div>
</div>

<footer>
	<div class="wrapper">
		Ribbit - A Twitter Clone Tutorial<img src="/gfx/logo-nettuts.png">
	</div>
</footer>
</body>
</html>

app/views/ribbits/_new_form.html.erb
<div class="panel right">
	<h1>Create A Ribbit</h1>
	<%= form_for @ribbit do |f| -%>
		<%= f.text_area :content, class: "ribbitText", id: "ribbitText" , :required => true %>
		<%= f.submit "Create" , id: "ribbitBtn" %>
		<span id="charCount">0</span>
	<% end -%>
</div>

app/views/ribbits/index.html.erb
<% if current_user %>
	<%= render "ribbits/new_form" %>
<% end -%>
<div id="ribbits" class="panel left">
	<h1>Public Ribbits</h1>
	<% @ribbits.each do |ribbit| %>
	<div class="ribbitWrapper">
		<img class="avatar" src="<%= ribbit.user.avatar_url %>">
			<span class="name"><%= link_to ribbit.user.name , ribbit.user %></span> @<%= ribbit.user.username %> 
			<span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
			<p>
				<%= ribbit.content %>
			</p>
	</div>
	<% end -%>				
</div>

<%= javascript_include_tag "ribbits" %>

app/views/users/buddies.html.erb
<% if current_user %>
	<%= render "ribbits/new_form" %>
<% end -%>
<div id="ribbits" class="panel left">
	<h1>Buddies Ribbits</h1>
	<% @ribbits.each do |ribbit| %>
	<div class="ribbitWrapper">
		<img class="avatar" src="<%= ribbit.user.avatar_url %>">
			<span class="name"><%= link_to ribbit.user.name , ribbit.user %></span> @<%= ribbit.user.username %> 
			<span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
			<p>
				<%= ribbit.content %>
			</p>
	</div>
	<% end -%>				
</div>

<%= javascript_include_tag "ribbits" %>

app/views/users/mentions.html.erb
<% if current_user %>
	<%= render "ribbits/new_form" %>
<% end -%>
<div id="ribbits" class="panel left">
	<h1>Mention Ribbits</h1>
	<% @ribbits.each do |ribbit| %>
	<div class="ribbitWrapper">
		<img class="avatar" src="<%= ribbit.user.avatar_url %>">
			<span class="name"><%= link_to ribbit.user.name , ribbit.user %></span> @<%= ribbit.user.username %> 
			<span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
			<p>
				<%= ribbit.content %>
			</p>
	</div>
	<% end -%>				
</div>

<%= javascript_include_tag "ribbits" %>

app/views/users/new.html.erb
<img src="/gfx/frog.jpg">
<div class="panel right">
	<h1>New to Ribbit?</h1>
	<p>
	<%= form_for @user do |f| -%>
	<% if @user.errors.any? %>
		<ul>
			<% @user.errors.full_messages.each do |e| %>
			<li> <%= e %> </li>
			<% end -%>
		</ul>
	<% end -%>
	<%= f.text_field :email, placeholder: "email" %>
	<%= f.text_field :username, placeholder: "username" %>
	<%= f.text_field :name, placeholder: "name" %>
	<%= f.password_field :password , placeholder: "password" %>
	<%= f.password_field :password_confirmation , placeholder: "confrim password" %>
	<%= f.submit "Create Account" %>
	<% end -%>
	</p>
</div>

app/views/users/show.html.erb
<% if current_user %>
	<%= render 'ribbits/new_form' %>
<% end -%>
<div id="ribbits" class="panel left">
	<h1>Your Ribbit Profile</h1>
	<div class="ribbitWrapper">
		<img class="avatar" src="<%= @user.avatar_url %>">
		<span class="name"><%= @user.name %></span> @<%= @user.username %>
		<p>
			<%= @user.ribbits.length %> Ribbits
			<span class="spacing"><%= @user.followers.length %> Followers</span>
			<span class="spacing"><%= @user.followeds.length %> Following</span>

			<% if current_user && @user != current_user %>
				<% if current_user.following @user %>
					<%= form_for @relationship , method: :delete do |f| -%>
						<%= f.submit "UnFollow" %>
					<% end -%>
				<% else %>
					<%= form_for @relationship do |f| -%>
						<%= f.hidden_field :followed_id , value: @user.id %>
						<%= f.submit "Follow" %>
					<% end -%>
				<% end -%>
			<% end -%>


		</p>
	</div>
</div>
<div class="panel left">
	<h1>Ribbts</h1>
	<% @user.ribbits.each do |ribbit| %>
	<div class="ribbitWrapper">
		<img class="avatar" src="<%= @user.avatar_url %>">
		<span class="name"><%= @user.name %></span> @<%= @user.username %> 
		<span class="time"><%= time_ago_in_words(ribbit.created_at) %></span>
		<p>
			<%= ribbit.content %>
		</p>
	</div>
	<% end -%>
</div>

<%= javascript_include_tag "ribbits" %>